using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MenuLilypad : MonoBehaviour
{
    // create a random direction in the x-z plane for starting movement
    // have a constant speed
    // when it reaches the edge of the screen, change direction
    // if bumps into another lilypad, change direction

    public float speed = 0.25f;
    public Vector3 direction;
    public AudioClip collideClip;
    private Rigidbody rb;
    private Vector3 viewportPos;
    private Camera mainCamera;
    private float edgeThreshold = 0.001f;
    private void Awake()
    {
        rb = GetComponent<Rigidbody>();
    }
    private void Start()
    {
        direction = new Vector3(Random.Range(-1f, 1f), 0, Random.Range(-1f, 1f));
        rb.velocity = direction.normalized * speed;
        rb.angularVelocity = Random.insideUnitSphere;
        mainCamera = Camera.main;
    }

    private void FixedUpdate()
    {
        viewportPos = mainCamera.WorldToViewportPoint(transform.position);

        // Check if the object is at the edge of the screen
        bool atLeftEdge = viewportPos.x <= edgeThreshold;
        bool atRightEdge = viewportPos.x >= 1 - edgeThreshold;
        bool atBottomEdge = viewportPos.y <= edgeThreshold;
        bool atTopEdge = viewportPos.y >= 1 - edgeThreshold;

        if (atLeftEdge)
        {
            direction = new Vector3(Mathf.Abs(direction.x), 0, direction.z);
        }
        if (atRightEdge)
        {
            direction = new Vector3(-Mathf.Abs(direction.x), 0, direction.z);
        }
        if (atBottomEdge)
        {
            direction = new Vector3(direction.x, 0, Mathf.Abs(direction.z));
        }
        if (atTopEdge)
        {
            direction = new Vector3(direction.x, 0, -Mathf.Abs(direction.z));
        }
        rb.velocity = Vector3.zero;
        rb.velocity = direction.normalized * speed;
    }

    private void OnCollisionEnter(Collision collision)
    {
        direction = collision.GetContact(0).normal;
        direction = new Vector3(direction.x, 0, direction.z);
        direction = direction.normalized;
        Rigidbody otherRb = collision.rigidbody; // The other object
        Vector3 relativeVelocity = rb.velocity - (otherRb ? otherRb.velocity : Vector3.zero);

        // Calculate the point of contact relative to the object's center of mass
        Vector3 contactPoint = collision.GetContact(0).point - transform.position;

        // Calculate torque generated by the collision
        Vector3 torque = Vector3.Cross(contactPoint, relativeVelocity);

        // Adjust torque based on mass and inertia
        float angularEffect = 1.25f; // Adjust this factor to control angular velocity
        Vector3 angularVelocityChange = torque * angularEffect / rb.mass;

        // Apply calculated angular velocity
        rb.angularVelocity += angularVelocityChange;

        // Update direction based on collision normal
        direction = collision.GetContact(0).normal;
        direction = new Vector3(direction.x, 0, direction.z).normalized;
        rb.velocity = direction.normalized * speed;

        PlayCollideClip();
    }

    void PlayCollideClip()
    {
        if (collideClip == null)
        {
            return;
        }
        AudioManager.Instance.KillSFX(collideClip);
        AudioSource source = AudioManager.Instance.PlaySFX(collideClip);
        source.pitch += Random.Range(-0.1f, 0.1f);
    }
}
